language: node_js
node_js:
  - "10"
cache: npm
before_script:
  - npm install
script: 'npm run build --report'
# Send notification to Slack
notifications:
  slack:
    secure: "DzlGbjwghAH1axfK7LJC8c2WW8aQSUVAwakU6l2QZB+7w/cDGf2mAdgy5JOkdp9jcuDUfJjNcqrcNQStKRb7oKg13NUgeQeoRgZm1H0lBYvEVutkvBwrSxWyu7EH0hwEdUAFussnkqk0r5PTeCe+hQaOXg16jlA+aBchj3Ld41Cv5hogrCiAPIa+7VU1NHCJ0ak3mQ2E17TVExhAhlIKGT2Ae4f75TfYZ1YzwebzGmFdks1g/Qy96sGNpZ+LKP12v4HJLYATsW2KO7G7TAj9yZYqIJZJKwNBeJ6saP2Q1RWPpmwDKEhJoMgLj4trOZVsDG/8W1iYLml43vHpx8NNShafUlxbZoK8a5IEpRzZt7xE8nMo7gkgWlRl5gJ1rPNlqIRTxKc56jsXmtvr/c24+F6gzgvPnE8Yxb7mdWs6kxmPz/6qnVeAPXqFitJgqh9zes6EZ4EIvbv9RYc7uMezMTxmRMVFnkPhA4ijaC0mwQMBUBWcj1fwhxAHkKA/0fart4PmF47jLPfiJGHS/CMVBSrxKswxxPs8gCvJ67IWVUNj0fI5F/915d0sA4q770mIHP6vrPMnpJTpQ9smlCbWLwdNWDRG7TbOlVijLBvAXjLxpwqYuoQfEm8jb1fCHEsq+xFRPE34wkeBbrXM0ziJXPVxQXDzeyPSNpcsA+jB5/M="
