<template>
  <div style="padding: 1em;">
    <!-- <p>isArray: {{ isArray }}</p> -->
    <!-- <p>isMap: {{ isMap }}</p> -->
    <div v-if="isArray">
      <div v-for="(levelDataItem, index) in levelData" v-bind:key="index">
        <AutoGeneratedFormLevel
          :interfaces="interfaces"
          :interfaceKey="interfaceKey"
          :isArray="false"
          :isMap="false"
          :levelData="levelDataItem"
          :level="(level + 1)"
        />
      </div>
    </div>
    <div v-else-if="isMap">
      <div v-for="(levelDataItemKey, index) in Object.keys(levelData)" v-bind:key="index">
        <AutoGeneratedFormLevel
          :interfaces="interfaces"
          :interfaceKey="interfaceKey"
          :isArray="false"
          :isMap="false"
          :levelData="levelData[levelDataItemKey]"
          :level="(level + 1)"
        />
      </div>
    </div>
    <div v-else>
      <div v-for="(formElement, index) in formElements" v-bind:key="index">
        <div v-if="interfaces[interfaceKey][formElement].type === 'string'">
          <div v-if="interfaces[interfaceKey][formElement].Markdown">
            <b-form-group
              :label="`${formElement}${interfaces[interfaceKey][formElement].Required ? '*' : ''}:`"
            >
              <b-form-textarea
                :value="levelData[formElement]"
                :placeholder="formElement"
                :rows="3"
                :max-rows="6"
              >
              </b-form-textarea>
            </b-form-group>
          </div>
          <div v-else>
            <b-form-group
              :label="`${formElement}${interfaces[interfaceKey][formElement].Required ? '*' : ''}:`"
            >
              <b-form-input
                type="text"
                :placeholder="formElement"
                :value="levelData[formElement]"
              >
              </b-form-input>
            </b-form-group>
          </div>
        </div>
        <div v-else-if="interfaces[interfaceKey][formElement].type === 'boolean'">
          <b-form-group>
            <b-form-checkbox-group>
              <b-form-checkbox 
                :value="true"
                :unchecked-value="false"
              >
                {{ formElement }}
              </b-form-checkbox>
            </b-form-checkbox-group>
          </b-form-group>
        </div>
        <div v-else-if="interfaces[interfaceKey][formElement].type === 'primitive'">
          {{ formElement }}: primitive
        </div>
        <div v-else-if="interfaces[interfaceKey][formElement].type === 'Any'">
          {{ formElement }}: Any
        </div>
        <div v-else>
          <label>{{ formElement }}:</label>
          <AutoGeneratedFormLevel
            v-if="interfaces[interfaceKey][formElement].type && level < 6"
            :interfaces="interfaces"
            :interfaceKey="interfaces[interfaceKey][formElement].type"
            :isArray="interfaces[interfaceKey][formElement].Array"
            :isMap="interfaces[interfaceKey][formElement].Map"
            :levelData="levelData[formElement]"
            :level="(level + 1)"
          />
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'AutoGeneratedFormLevel',
  props: {
    interfaces: {
      type: Object,
      required: true,
    },
    interfaceKey: {
      type: String,
      required: true,
    },
    levelData: {
      required: false,
      default() { return {}; },
    },
    level: {
      type: Number,
      required: true,
    },
    isArray: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
    isMap: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
  },
  components: {
  },
  computed: {
    formElements() {
      const { interfaces, interfaceKey } = this;
      if (!interfaceKey) {
        return [];
      } else if (
        interfaceKey === 'string' ||
        interfaceKey === 'boolean' ||
        interfaceKey === 'primitive' ||
        interfaceKey === 'Any'
      ) {
        return [interfaceKey];
      }
      // if (!interfaces[interfaceKey]) {
      //   console.log(interfaceKey, interfaces[interfaceKey]);
      // }
      return Object.keys(interfaces[interfaceKey]);
    },
  },
};
</script>