<template>
  <div>
    <div style="position: relative" v-if="levelTitle">
      <b-link class="collapse-button" @click="handleCollapse" v-if="isCollapsible">
        <Icon :icon="isCollapsed ? 'minus-square' : 'plus-square'" />
      </b-link>
      <legend>{{ levelTitle }}</legend>
    </div>
    <div v-if="!isCollapsible || (isCollapsible && isCollapsed)">
      <div class="form-level">
        <div v-if="isMap || isArray || isMapWithRegex">
          <div v-for="(levelDataItemKey, index) in Object.keys(levelData)" v-bind:key="index">
            <AutoGeneratedFormLevel
              :interfaces="interfaces"
              :interfaceKey="isMapWithRegex ? getRegexInterfaceKey(levelDataItemKey) : interfaceKey"
              :isArray="false"
              :isMap="false"
              :isCollapsible="(interfaceKey !== 'string')"
              :levelData="(interfaceKey !== 'string') ? levelData[levelDataItemKey] : { string: levelData[levelDataItemKey]}"
              :levelTitle="levelDataItemKey"
              :level="(level + 1)"
            />
          </div>
        </div>
        <div v-else>
          <div v-for="(formElement, index) in formElements" v-bind:key="index">
            <div
              v-if="
                (
                  getElementType(formElement) === 'string' ||
                  getElementType(formElement) === 'primitive'
                ) && !isElementArray(formElement)
              "
            >
              <div v-if="isElementMarkdown(formElement)">
                <b-form-group
                  :label="`${formElement}${isElementRequired(formElement) ? '*' : ''}:`"
                >
                  <b-form-textarea
                    :value="levelData[formElement]"
                    :placeholder="formElement"
                    :rows="3"
                    :max-rows="6"
                  >
                  </b-form-textarea>
                </b-form-group>
              </div>
              <div v-else>
                <b-form-group
                  :label="`${formElement}${isElementRequired(formElement) ? '*' : ''}:`"
                >
                  <!-- {{ levelData }} -->
                  <b-form-input
                    type="text"
                    :placeholder="formElement"
                    :value="levelData[formElement]"
                  >
                  </b-form-input>
                </b-form-group>
              </div>
            </div>
            <div v-else-if="getElementType(formElement) === 'boolean'">
              <legend></legend>
              <b-form-group>
                <b-form-checkbox-group>
                  <b-form-checkbox 
                    :value="true"
                    :unchecked-value="false"
                  >
                    {{ formElement }}
                  </b-form-checkbox>
                </b-form-checkbox-group>
              </b-form-group>
            </div>
            <div v-else-if="getElementType(formElement) === 'Any'">
              {{ formElement }}: Any
            </div>
            <div v-else>
              <AutoGeneratedFormLevel
                v-if="getElementType(formElement)"
                :interfaces="interfaces"
                :interfaceKey="getElementType(formElement)"
                :isArray="isElementArray(formElement)"
                :isMap="isElementMap(formElement)"
                :isMapWithRegex="isElementMapWithRegex(formElement)"
                :isCollapsible="true"
                :levelData="levelData[formElement]"
                :levelTitle="formElement"
                :level="(level + 1)"
              />
            </div>
          </div>
        </div>
        <div v-if="isMap || isArray || isMapWithRegex">
          <legend>Add "{{ interfaceKey }}"</legend>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Icon from '@/components/shared/Icon';

export default {
  name: 'AutoGeneratedFormLevel',
  props: {
    interfaces: {
      type: Object,
      required: true,
    },
    interfaceKey: {
      type: String,
      required: true,
    },
    levelData: {
      required: false,
      default() { return {}; },
    },
    levelTitle: {
      type: String,
      required: false,
    },
    level: {
      type: Number,
      required: true,
    },
    isArray: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
    isMap: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
    isMapWithRegex: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
    isCollapsible: {
      type: Boolean,
      required: false,
      default() { return false; },
    },
  },
  components: {
    Icon,
  },
  computed: {
    formElements() {
      const { interfaces, interfaceKey } = this;
      if (!interfaceKey) {
        return [];
      } else if (
        interfaceKey === 'string' ||
        interfaceKey === 'boolean' ||
        interfaceKey === 'primitive' ||
        interfaceKey === 'Any'
      ) {
        return [interfaceKey];
      }
      // if (!interfaces[interfaceKey]) {
      //   console.log(interfaceKey, interfaces[interfaceKey]);
      // }
      return Object.keys(interfaces[interfaceKey]);
    },
  },
  data() {
    return {
      isCollapsed: false,
    };
  },
  methods: {
    handleCollapse() {
      this.isCollapsed = !this.isCollapsed;
    },
    getRegexInterfaceKey(propName) {
      const { interfaceKey, interfaces } = this;
      return Object.keys(interfaces[interfaceKey]).map(item => ({
        key: item,
        ...interfaces[interfaceKey][item],
      }))
      .filter(item => item.regex)
      .find(item => Boolean(propName.match(new RegExp(item.regex), 'g'))).type;
    },
    getElementType(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return 'string';
      }
      return interfaces[interfaceKey][formElement].type;
    },
    isElementArray(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return false;
      }
      return interfaces[interfaceKey][formElement].Array;
    },
    isElementMap(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return false;
      }
      return interfaces[interfaceKey][formElement].Map;
    },
    isElementMapWithRegex(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return false;
      }
      return interfaces[interfaceKey][formElement].MapWithRegex;
    },
    isElementMarkdown(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return false;
      }
      return interfaces[interfaceKey][formElement].Markdown;
    },
    isElementRequired(formElement) {
      const { interfaces, interfaceKey } = this;
      if (interfaceKey === 'string') {
        return false;
      }
      return interfaces[interfaceKey][formElement].Required;
    },
  },
};
</script>

<style lang="scss">
.form-level {
  border-left: 5px solid #00adee;
  padding-left: 1em;
  padding-top: .5em;
  padding-bottom: .5em;
}

.collapse-button {
  position: absolute;
  top: 4px;
  left: -27px;
  line-height: 0;
  background-color: white;
  border: 1px solid white;
  z-index: 1;
}

legend {
  position: relative;
  font-size: 1em;

  &::after {
    content: " ";
    position: absolute;
    top: 10px;
    left: -1em;
    border-top: 5px solid #00adee;
    width: .9em;
  }
}
</style>