<template>
  <div style="padding: .5em;">
    <b-form>
      <AutoGeneratedFormLevel
        :interfaces="interfaces"
        :interfaceKey="formData.interfaceKey"
        :isArray="formData.isArray"
        :isMap="formData.isMap"
        :isCollapsible="false"
        :levelData="formData.propData"
        levelTitle="Root"
        :level="0"
      />
    </b-form>
  </div>
</template>

<script>
import AutoGeneratedFormLevel from '@/components/shared/autoGeneratedForm/AutoGeneratedFormLevel';

export default {
  props: {
    formData: {
      type: [Object, Array],
      required: true,
    },
    interfaces: {
      type: Object,
      required: true,
    },
  },
  components: {
    AutoGeneratedFormLevel,
  },
};
</script>